#!/usr/bin/env php
<?php

if(!is_dir("./storage/Centauri/Domains")) {
    mkdir("./storage/Centauri/Domains");
}

$domainFiles = array_diff(
    scandir("./storage/Centauri/Domains"),

    [
        ".",
        ".."
    ]
);

if(count($domainFiles) == 0) {
    $data = [
        "id" => "Main",
        "ssl" => false,
        "domain" => "centauri.dev",
        "rootpageuid" => "1",
        "pageNotFound" => ""
    ];

    file_put_contents("./storage/Centauri/Domains/main.json", json_encode($data, JSON_PRETTY_PRINT));
}
